#!/usr/bin/env node
// Refreshes vendor/duckdb-wasm/ from the installed @duckdb/duckdb-wasm package.
// Run locally by a maintainer after bumping the pinned version in package.json,
// then commit the updated vendor/ folder.
//
// We deliberately copy ONLY the non-threaded browser bundles (mvp + eh).
// GitHub Pages cannot set COOP/COEP headers, so SharedArrayBuffer is unavailable
// and the coi/pthread bundles would fail at runtime.
//
// The upstream ESM entrypoint imports `apache-arrow` as a bare specifier, which
// browsers cannot resolve without an import map. We use esbuild to produce a
// fully self-contained ESM bundle (`duckdb-browser.mjs`) with apache-arrow
// inlined — so the site only needs to import a single relative file at runtime.

import { mkdir, copyFile, writeFile, rm, readFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const vendorDir = resolve(repoRoot, 'vendor', 'duckdb-wasm');

const pkgRoot = resolve(repoRoot, 'node_modules', '@duckdb', 'duckdb-wasm');
const pkgJsonPath = resolve(pkgRoot, 'package.json');
const pkg = JSON.parse(await readFile(pkgJsonPath, 'utf8'));
const distDir = resolve(pkgRoot, 'dist');

const arrowPkg = JSON.parse(
  await readFile(resolve(repoRoot, 'node_modules', 'apache-arrow', 'package.json'), 'utf8')
);

// Static files copied verbatim (no transform needed). The ESM main entry is
// produced by esbuild below; do NOT copy duckdb-browser.mjs here.
const FILES_TO_COPY = [
  'duckdb-browser-mvp.worker.js',
  'duckdb-browser-eh.worker.js',
  'duckdb-mvp.wasm',
  'duckdb-eh.wasm',
];

console.log(
  `Refreshing ${vendorDir} from @duckdb/duckdb-wasm@${pkg.version}`
  + ` (+ apache-arrow@${arrowPkg.version} bundled)`
);

if (existsSync(vendorDir)) {
  await rm(vendorDir, { recursive: true, force: true });
}
await mkdir(vendorDir, { recursive: true });

for (const file of FILES_TO_COPY) {
  const src = resolve(distDir, file);
  const dst = resolve(vendorDir, file);
  if (!existsSync(src)) {
    throw new Error(`Expected ${file} in ${distDir} but it was missing`);
  }
  await copyFile(src, dst);
  console.log(`  + ${file}`);
}

// Bundle the browser ESM entrypoint with apache-arrow inlined.
const requireFromHere = createRequire(import.meta.url);
const esbuild = requireFromHere('esbuild');
const browserEsmEntry = resolve(distDir, 'duckdb-browser.mjs');
const bundleOut = resolve(vendorDir, 'duckdb-browser.mjs');
await esbuild.build({
  entryPoints: [browserEsmEntry],
  outfile: bundleOut,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2020'],
  minify: false,
  sourcemap: false,
  // duckdb-wasm picks the worker URL at runtime from its argument; the worker
  // script itself is a separate file we copy above. esbuild must NOT try to
  // inline workers — they have to remain separately fetchable .js files.
  external: [],
  legalComments: 'none',
  logLevel: 'info',
});
const sz = (await stat(bundleOut)).size;
console.log(`  + duckdb-browser.mjs (bundled, ${(sz / 1024).toFixed(1)} KiB)`);

const noticeLines = [
  `@duckdb/duckdb-wasm version ${pkg.version}`,
  `License: ${pkg.license ?? 'MIT'} (per package.json)`,
  '',
  `apache-arrow version ${arrowPkg.version} (bundled into duckdb-browser.mjs)`,
  `License: ${arrowPkg.license ?? 'Apache-2.0'} (per package.json)`,
  '',
  'Upstream license text:',
  '  https://github.com/duckdb/duckdb-wasm/blob/main/LICENSE',
  '  https://github.com/duckdb/duckdb/blob/main/LICENSE',
  '  https://github.com/apache/arrow/blob/main/LICENSE.txt',
  '',
  'This folder is regenerated by scripts/update-vendor.mjs.',
];
await writeFile(resolve(vendorDir, 'VERSION.txt'), noticeLines.join('\n') + '\n', 'utf8');

console.log('Done. Review changes and commit vendor/.');
